### ISSUE TITLE
Implementations Task Checklist

### ISSUE THREAD

**Issue by mesadhan** [mesadhan/android-oauth2-sample#2]
- [x] Create an Android Application.
- [x] Install library.
- [x] Need some basic configuration.
- [x] Coding Implementation.
- [x] Run and test application

**Comment by mesadhan** [comment]
Result working as expected
